## Pockets Label

In [1]:
# demo for a pdb to generate a graph
import torch
import pandas as pd
from torchdrug import data, layers

In [2]:
pre = "../../../data/dta-datasets/PDBbind/"
pdb_name = "1a0q"
csv_path = pre + "PDBbind_file/" + pdb_name + "/" + pdb_name + "_proteins.csv"

In [3]:
pdb_residues = pd.read_csv(csv_path)
pdb_residues.columns = pdb_residues.columns.str.strip()  # 原始表格列名有空格，这里去除方便索引
pdb_residues

chain  residue_label residue_name  pocket
0       L              2          ILE       0
1       L              3          GLU       0
2       L              4          LEU       0
3       L              5          THR       0
4       L              6          GLN       0
..    ...            ...          ...     ...
411     H            207          ASP       0
412     H            208          LYS       0
413     H            209          LYS       0
414     H            210          ILE       0
415     H            211          GLU       0

[416 rows x 4 columns]

首先获取pocket的数量，从`pocket`列获取不重复数字，即不重复的口袋数量，目的是获取非0（0表示该氨基酸不属于任何一个口袋）的子图。

In [4]:
pocket_list = pdb_residues["pocket"].unique()
pocket_list

array([0, 1], dtype=int64)

通过条件索引分别得到pocket=1的氨基酸索引

In [5]:
pdb_residues[pdb_residues["pocket"] == 1].index.tolist()

[30,
 31,
 32,
 33,
 34,
 42,
 44,
 45,
 46,
 47,
 48,
 49,
 53,
 86,
 87,
 88,
 89,
 90,
 92,
 93,
 94,
 95,
 241,
 242,
 243,
 244,
 245,
 246,
 254,
 255,
 256,
 257,
 258,
 259,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 312,
 313,
 314]

In [7]:
current_pocket = pdb_residues[pdb_residues["pocket"] == 1].index.tolist()
print(current_pocket)

[30, 31, 32, 33, 34, 42, 44, 45, 46, 47, 48, 49, 53, 86, 87, 88, 89, 90, 92, 93, 94, 95, 241, 242, 243, 244, 245, 246, 254, 255, 256, 257, 258, 259, 304, 305, 306, 307, 308, 309, 310, 312, 313, 314]


将蛋白质全长变成一个tensor，最好保存为一个pkl进行后续的使用。

In [9]:
pdb_residues.shape[0]

416

In [11]:
import torch

label = torch.zeros(pdb_residues.shape[0])
label

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [12]:
for index in current_pocket:
    label[index] = 1

In [13]:
label

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 

In [14]:
label.shape

torch.Size([416])

### Dataset Pockets

In [1]:
import pickle
import torch
from tqdm import tqdm
import pandas as pd
from torchdrug import data, utils

In [2]:
affinity_csv = '../../../data/dta-datasets/PDBbind/PDBbind_pocket/pdbbind_datasets.csv'
pre = "../../../data/dta-datasets/PDBbind"

In [3]:
pdbbind_affinities= pd.read_csv(affinity_csv)
pdbbind_affinities

PDB_ID                                               Drug  \
0       3ZZF                      CC(=O)N[C@@H](CCC(=O)O)C(=O)O   
1       3GWW        C[NH2+]CC[C@H](Oc1ccc(C(F)(F)F)cc1)c1ccccc1   
2       1W8L                             CC(=O)N1CCC[C@@H](C)C1   
3       3FQA                                  Nc1cccc(C(=O)O)c1   
4       1ZSB                         CC(=O)Nc1nnc(S(N)(=O)=O)s1   
...      ...                                                ...   
19349   7CPA  CC(C)[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)OCc1ccc...   
19350   2XUF  Nc1ccc2c(c1)C(c1ccccc1)N(CCCCCCc1cn(CCNc3c4ccc...   
19351   1AVD          O=C(O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@@H]21   
19352   2XUI  Nc1ccc2c(c1)C(c1ccccc1)N(CCCCCCc1cnnn1CCNc1c3c...   
19353   2AVI          O=C(O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@@H]21   

                                                  Target      Y  Drug_Index  \
0      NGFSATRSTVIQLLNNISTKREVEQYLKYFTSVSQQQFAVIKVGGA...   0.40           0   
1      REHWATRLGLILAMAGNAVGLGNFLRFPVQAAENGGGAFMIPYIIA...   0.45           1   
2      MVNPTVFFDIAVDGEPLGRVSFELFADKVPKTAENFRALSTGEKGF...   0.49           2   
3      KTIKSDEIFAAAQKLMPGGVSSPVRAFKSVGGQPIVFDRVKDAYAW...   0.49           3   
4      HWGYGKHNGPEHWHKDFPIAKGERQSPVDIDTHTAKYDPSLKPLSV...   0.60           4   
...                                                  ...    ...         ...   
19349  ARSTNTFNYATYHTLDEIYDFMDLLVAQHPELVSKLQIGRSYEGRP...  13.96       19349   
19350  REDPQLLVRVRGGQLRGIRLKAPGGPVSAFLGIPFAEPPVGSRRFM...  14.39       19350   
19351  KCSLTGKWTNDLGSNMTIGAVNSRGEFTGTYTTAVTATSNEIKESP...  15.00       19351   
19352  EGREDPQLLVRVRGGQLRGIRLKAPGGPVSAFLGIPFAEPPVGSRR...  15.00       19352   
19353  KCSLTGKWTNDLGSNMTIGAVNSRGEFTGTYTTAVTATSNEIKESP...  15.22       19353   

       Protein_Index  
0                  0  
1                  1  
2                  2  
3                  3  
4                  4  
...              ...  
19349          19403  
19350          19404  
19351          19405  
19352          19406  
19353          19407  

[19354 rows x 6 columns]

In [5]:
label_list = []
for pdb in tqdm(pdbbind_affinities.PDB_ID):
    pdb_name = pdb.lower()
    csv_path = pre + "/PDBbind_file/" + pdb_name + "/" + pdb_name + "_proteins.csv"
    pdb_residues = pd.read_csv(csv_path)
    pdb_residues.columns = pdb_residues.columns.str.strip()  # 原始表格列名有空格，这里去除方便索引
    current_pocket = pdb_residues[pdb_residues["pocket"] == 1].index.tolist()
    label = torch.zeros(pdb_residues.shape[0])
    for index in current_pocket:
        label[index] = 1
    label_list.append(label)

100%|██████████| 19354/19354 [02:41<00:00, 119.54it/s]


In [7]:
len(label_list)

19354

In [8]:
label_pkl = '../../../data/dta-datasets/PDBbind/PDBbind_pocket/pocket_label.pkl'
with utils.smart_open(label_pkl, "wb") as fout:
    pickle.dump(label_list, fout)