## Pocket Label process

In [2]:
import torch
import pickle
from torchdrug import data, utils

In [3]:
pre = "../../../data/dta-datasets/PDBbind"

In [4]:
protein_pkl = pre + '/pocket_Protein.pkl'

In [5]:
with utils.smart_open(protein_pkl, "rb") as fin:
    pocket_list = pickle.load(fin)

In [6]:
pocket_list

[Protein(num_atom=390, num_bond=790, num_residue=39),
 Protein(num_atom=222, num_bond=428, num_residue=22),
 Protein(num_atom=350, num_bond=618, num_residue=62),
 Protein(num_atom=492, num_bond=962, num_residue=51),
 Protein(num_atom=723, num_bond=1408, num_residue=80),
 Protein(num_atom=459, num_bond=906, num_residue=46),
 Protein(num_atom=705, num_bond=1380, num_residue=76),
 Protein(num_atom=321, num_bond=586, num_residue=55),
 Protein(num_atom=275, num_bond=552, num_residue=27),
 Protein(num_atom=527, num_bond=1040, num_residue=53),
 Protein(num_atom=441, num_bond=862, num_residue=44),
 Protein(num_atom=396, num_bond=790, num_residue=43),
 Protein(num_atom=384, num_bond=768, num_residue=41),
 Protein(num_atom=552, num_bond=1084, num_residue=58),
 Protein(num_atom=539, num_bond=1056, num_residue=56),
 Protein(num_atom=152, num_bond=298, num_residue=16),
 Protein(num_atom=475, num_bond=930, num_residue=54),
 Protein(num_atom=454, num_bond=894, num_residue=46),
 Protein(num_atom=454, 

In [7]:
len(pocket_list)

9018

In [9]:
pocket = pocket_list[0]
pocket

Protein(num_atom=390, num_bond=790, num_residue=39)

In [10]:
pocket.residue_number

tensor([243, 248, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
        486, 495, 496, 497, 498, 502, 503, 504, 505, 506, 507, 508, 509, 510,
        511, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571])

### Test Zone for Residue mapping

residue sequence

In [1]:
from Bio import PDB
import warnings

warnings.filterwarnings("ignore")
pre = "../../../data/dta-datasets/PDBbind/PDBbind_file/"

In [4]:
# 创建PDB解析器
parser = PDB.PDBParser()
# 读取PDB文件
structure = parser.get_structure("1n4k", pre + "1n4k/1n4k_protein.pdb")
structure

<Structure id=1n4k>

In [9]:
# 提取残基序列信息
residues = []
for model in structure:
    for chain in model:
        for residue in chain:
            print(residue.get_id())
            if residue.get_id()[0] != " ":
                # print(residue.get_id()[0])
                continue
            elif PDB.is_aa(residue):
                residues.append(PDB.Polypeptide.three_to_one(residue.get_resname()))

(' ', 236, ' ')
(' ', 237, ' ')
(' ', 238, ' ')
(' ', 239, ' ')
(' ', 240, ' ')
(' ', 241, ' ')
(' ', 242, ' ')
(' ', 243, ' ')
(' ', 244, ' ')
(' ', 245, ' ')
(' ', 246, ' ')
(' ', 247, ' ')
(' ', 248, ' ')
(' ', 249, ' ')
(' ', 250, ' ')
(' ', 251, ' ')
(' ', 252, ' ')
(' ', 253, ' ')
(' ', 254, ' ')
(' ', 255, ' ')
(' ', 256, ' ')
(' ', 257, ' ')
(' ', 258, ' ')
(' ', 259, ' ')
(' ', 260, ' ')
(' ', 261, ' ')
(' ', 262, ' ')
(' ', 263, ' ')
(' ', 264, ' ')
(' ', 265, ' ')
(' ', 266, ' ')
(' ', 267, ' ')
(' ', 268, ' ')
(' ', 269, ' ')
(' ', 270, ' ')
(' ', 271, ' ')
(' ', 272, ' ')
(' ', 273, ' ')
(' ', 274, ' ')
(' ', 275, ' ')
(' ', 276, ' ')
(' ', 277, ' ')
(' ', 278, ' ')
(' ', 279, ' ')
(' ', 280, ' ')
(' ', 281, ' ')
(' ', 282, ' ')
(' ', 283, ' ')
(' ', 284, ' ')
(' ', 285, ' ')
(' ', 286, ' ')
(' ', 287, ' ')
(' ', 288, ' ')
(' ', 302, ' ')
(' ', 303, ' ')
(' ', 304, ' ')
(' ', 305, ' ')
(' ', 306, ' ')
(' ', 307, ' ')
(' ', 308, ' ')
(' ', 309, ' ')
(' ', 310, ' ')
(' ', 31

In [6]:
# 打印残基序列
sequence = ''.join(residues)
print(sequence)

GGDVVRLFHAEQEKFLTCDEHRKKQHVFLRTTGRQSATSATSSKALWEVEVVQLFRFKHLATGHYLAAEVDMVYSLVSVPEGNDISSIFELDPYVRLRHLCTNTWVHSTNIPIDKEEEKPVMLKIGTSPLKEDKEAFAIVPVSPAEVRDLDFANDASKVLGSIAGKLEKGTITQNERRSVTKLLEDLVYFVTGGTNSGQDVLEVVFSKPNRERQKLMREQNILKQIFKLLQAPFTHAPFRHICRLCYRVLRHSQQDYRKNQEYIAKQFGFMQKQIGYDVLAEDTITALLHNN


In [7]:
len("GGDVVRLFHAEQEKFLTCDEHRKKQHVFLRTTGRQSATSATSSKALWEVEVVQLFRFKHLATGHYLAAEVDMVYSLVSVPEGNDISSIFELDPYVRLRHLCTNTWVHSTNIPIDKEEEKPVMLKIGTSPLKEDKEAFAIVPVSPAEVRDLDFANDASKVLGSIAGKLEKGTITQNERRSVTKLLEDLVYFVTGGTNSGQDVLEVVFSKPNRERQKLMREQNILKQIFKLLQAPFTHAPFRHICRLCYRVLRHSQQDYRKNQEYIAKQFGFMQKQIGYDVLAEDTITALLHNN")

292

protein residue index

In [1]:
from Bio import PDB
import warnings

warnings.filterwarnings("ignore")
pre = "../../../data/dta-datasets/PDBbind/PDBbind_file/"

In [2]:
# 创建PDB解析器
parser = PDB.PDBParser()
# 读取PDB文件
structure = parser.get_structure("1a0t", pre + "1a0t/1a0t_protein.pdb")
structure

<Structure id=1a0t>

In [3]:
# 提取残基的索引序号
protein_indices = []
for model in structure:
    for chain in model:
        for residue in chain:
            if PDB.is_aa(residue):
                protein_indices.append(chain.get_id() + "_" + str(residue.get_id()[1]))

In [4]:
# 打印残基的索引序号
print(protein_indices)

['P_71', 'P_72', 'P_73', 'P_74', 'P_75', 'P_76', 'P_77', 'P_78', 'P_79', 'P_80', 'P_81', 'P_82', 'P_83', 'P_84', 'P_85', 'P_86', 'P_87', 'P_88', 'P_89', 'P_90', 'P_91', 'P_92', 'P_93', 'P_94', 'P_95', 'P_96', 'P_97', 'P_98', 'P_99', 'P_100', 'P_101', 'P_102', 'P_103', 'P_104', 'P_105', 'P_106', 'P_107', 'P_108', 'P_109', 'P_110', 'P_111', 'P_112', 'P_113', 'P_114', 'P_115', 'P_116', 'P_117', 'P_118', 'P_119', 'P_120', 'P_121', 'P_122', 'P_123', 'P_124', 'P_125', 'P_126', 'P_127', 'P_128', 'P_129', 'P_130', 'P_131', 'P_132', 'P_133', 'P_134', 'P_135', 'P_136', 'P_137', 'P_138', 'P_139', 'P_140', 'P_141', 'P_142', 'P_143', 'P_144', 'P_145', 'P_146', 'P_147', 'P_148', 'P_149', 'P_150', 'P_151', 'P_152', 'P_153', 'P_154', 'P_155', 'P_156', 'P_157', 'P_158', 'P_159', 'P_160', 'P_161', 'P_162', 'P_163', 'P_164', 'P_165', 'P_166', 'P_167', 'P_168', 'P_169', 'P_170', 'P_171', 'P_172', 'P_173', 'P_174', 'P_175', 'P_176', 'P_177', 'P_178', 'P_179', 'P_180', 'P_181', 'P_182', 'P_183', 'P_184', 'P

In [5]:
len(protein_indices)

1239

In [6]:
protein_indices.index("P_76")

5

pocket residue index(within 10A of the ligand)

In [1]:
from Bio import PDB
import warnings

warnings.filterwarnings("ignore")
pre = "../../../data/dta-datasets/PDBbind/PDBbind_file/"

In [7]:
# 创建PDB解析器
parser = PDB.PDBParser()
# 读取PDB文件
structure = parser.get_structure("1a0t", pre + "1a0t/1a0t_pocket.pdb")
structure

<Structure id=1a0t>

In [8]:
# 提取残基的索引序号
pocket_indices = []
for model in structure:
    for chain in model:
        for residue in chain:
            if PDB.is_aa(residue):
                pocket_indices.append(chain.get_id() + "_" + str(residue.get_id()[1]))

In [9]:
# 打印残基的索引序号
print(pocket_indices)

['P_76', 'P_77', 'P_78', 'P_79', 'P_80', 'P_96', 'P_97', 'P_110', 'P_114', 'P_116', 'P_118', 'P_119', 'P_120', 'P_122', 'P_136', 'P_138', 'P_140', 'P_142', 'P_144', 'P_161', 'P_162', 'P_187', 'P_188', 'P_189', 'P_190', 'P_192', 'P_193', 'P_194', 'P_195', 'P_196', 'P_197', 'P_198', 'P_199', 'P_200', 'P_201', 'P_202', 'P_203', 'P_204', 'P_205', 'P_206', 'P_230', 'P_308', 'P_322', 'P_323', 'P_342', 'P_434', 'P_435', 'P_436', 'P_437', 'P_478', 'P_480', 'P_481', 'P_482', 'P_483', 'R_150', 'R_151']


In [10]:
len(pocket_indices)

56

In [11]:
mapping_list = []
for index in pocket_indices:
    mapping_list.append(protein_indices.index(index))

In [12]:
print(mapping_list)

[5, 6, 7, 8, 9, 25, 26, 39, 43, 45, 47, 48, 49, 51, 65, 67, 69, 71, 73, 90, 91, 116, 117, 118, 119, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 159, 237, 251, 252, 271, 363, 364, 365, 366, 407, 409, 410, 411, 412, 905, 906]


index mapping to output a tensor with 01

In [13]:
import numpy as np

In [14]:
pocket_label = np.zeros(len(protein_indices))
pocket_label

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
for index in mapping_list:
    pocket_label[index] = 1

In [18]:
pocket_label[5]

1.0

single pocket check

In [1]:
import warnings
from torchdrug import utils, data

warnings.filterwarnings("ignore")
pre = "../../../data/dta-datasets/PDBbind/PDBbind_file/"

In [2]:
pocket_file = pre + "1a0t/1a0t_pocket.pdb"
pocket_file

'../../../data/dta-datasets/PDBbind/PDBbind_file/1a0t/1a0t_pocket.pdb'

In [3]:
pocket = data.Protein.from_pdb(pocket_file, atom_feature=None, bond_feature=None, residue_feature="default", mol_feature=None)
pocket

Protein(num_atom=648, num_bond=1250, num_residue=74)

In [4]:
pocket.to_sequence()

'HGYAR.AY.R.Q.D.YVE.N.R.K.M.A.G.RQ.RFDR.NFDIHWIDSDVVFLA.R.K.KG.Y.FFSR.Q.ETWF.DW.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G'

In [8]:
pocket.to_sequence().replace(".", "")

'HGYARAYRQDYVENRKMAGRQRFDRNFDIHWIDSDVVFLARKKGYFFSRQETWFDWGGGGGGGGGGGGGGGGGG'

In [9]:
len("HGYARAYRQDYVENRKMAGRQRFDRNFDIHWIDSDVVFLARKKGYFFSRQETWFDW")

56

下面是处理位置残基的方法

```python
if type not in cls.residue2id:
    warnings.warn("Unknown residue `%s`. Treat as glycine" % type)
    type = "GLY"
```

Torchdrug mapping check

看看TorchDrug里的残基序列是不是对应输入的顺序，特别是这里进行过GearNet的重构。

In [ ]:
protein_pkl = '../../../data/dta-datasets/PDBbind/pocket_Protein.pkl'
with utils.smart_open(protein_pkl, "rb") as fin:
    protein_list = pickle.load(fin)

In [ ]:
protein_list

[Protein(num_atom=390, num_bond=790, num_residue=39),
 Protein(num_atom=222, num_bond=428, num_residue=22),
 Protein(num_atom=350, num_bond=618, num_residue=62),
 Protein(num_atom=492, num_bond=962, num_residue=51),
 Protein(num_atom=723, num_bond=1408, num_residue=80),
 Protein(num_atom=459, num_bond=906, num_residue=46),
 Protein(num_atom=705, num_bond=1380, num_residue=76),
 Protein(num_atom=321, num_bond=586, num_residue=55),
 Protein(num_atom=275, num_bond=552, num_residue=27),
 Protein(num_atom=527, num_bond=1040, num_residue=53),
 Protein(num_atom=441, num_bond=862, num_residue=44),
 Protein(num_atom=396, num_bond=790, num_residue=43),
 Protein(num_atom=384, num_bond=768, num_residue=41),
 Protein(num_atom=552, num_bond=1084, num_residue=58),
 Protein(num_atom=539, num_bond=1056, num_residue=56),
 Protein(num_atom=152, num_bond=298, num_residue=16),
 Protein(num_atom=475, num_bond=930, num_residue=54),
 Protein(num_atom=454, num_bond=894, num_residue=46),
 Protein(num_atom=454, 

In [ ]:
protein_list[6605].residue_type

tensor([18,  7,  0, 19, 18,  3,  8,  8,  7, 15, 18,  5,  8,  6,  8, 11, 18, 18,
         8, 17,  5, 16, 15,  4,  7, 15, 19,  4,  8, 13, 19,  7,  0, 18,  8,  6,
        12, 17,  0, 18, 18, 10, 18, 19,  0])